apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "maccabi-demo"
  description: "maccabi demo janus"
  annotations:
    argocd/app-name: maccabi-demo-dev
    backstage.io/kubernetes-id: maccabi-demo
    backstage.io/kubernetes-namespace: maccabi-demo-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: LiorJanus/maccabi-demo
    quay.io/repository-slug: "liorjanus/maccabi-demo"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-cl4w8.cl4w8.sandbox526.opentlc.com/#https://github.com/LiorJanus/maccabi-demo?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-cl4w8.cl4w8.sandbox526.opentlc.com/#https://github.com/LiorJanus/maccabi-demo?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "group:default/lior"
  providesApis:
    - "maccabi-demo"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "maccabi-demo"
  description: "maccabi demo janus"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/lior"
  definition:
    $text: ./openapi.yaml
